// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKadRhFDGH812ZW5Ksez537bowxdK2k8s',
    appId: '1:719225380662:web:578f6ba64de35f91d59d97',
    messagingSenderId: '719225380662',
    projectId: 'do-sprav-flutter-app',
    authDomain: 'do-sprav-flutter-app.firebaseapp.com',
    storageBucket: 'do-sprav-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7EmOc5mWd544HCmN9WQ_jTYwJHZYH46M',
    appId: '1:719225380662:android:0b9652a2bbf2de97d59d97',
    messagingSenderId: '719225380662',
    projectId: 'do-sprav-flutter-app',
    storageBucket: 'do-sprav-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJJ7uvLAySdkuPXHvx3AToimAV0ZNOhtk',
    appId: '1:719225380662:ios:d2afa60b82e8a4ead59d97',
    messagingSenderId: '719225380662',
    projectId: 'do-sprav-flutter-app',
    storageBucket: 'do-sprav-flutter-app.appspot.com',
    iosClientId: '719225380662-m16l49peq3ogt2lum746sncdtr1c41ov.apps.googleusercontent.com',
    iosBundleId: 'p.pavelko.job.dosprav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJJ7uvLAySdkuPXHvx3AToimAV0ZNOhtk',
    appId: '1:719225380662:ios:d2afa60b82e8a4ead59d97',
    messagingSenderId: '719225380662',
    projectId: 'do-sprav-flutter-app',
    storageBucket: 'do-sprav-flutter-app.appspot.com',
    iosClientId: '719225380662-m16l49peq3ogt2lum746sncdtr1c41ov.apps.googleusercontent.com',
    iosBundleId: 'p.pavelko.job.dosprav',
  );
}
